### ISSUE TITLE
Mistake in assertion statements in rc2lonlat

### ISSUE THREAD

**Issue by CarlMears** [CzendaZdenda/ease_lonlat#1]
e.g. line 219

```python
assert (lat >= -90.) & (lon <= 90.), f'latitude in {self.name} grid should be between -90 and 90'
```
"lon" should be "lat"

Also, I was initially confused when I got an error at the corners of the grid (row=0,col=0).  I my version, I 
changed the code to return a np.nan in this case, but maybe Ok to leave as is and use try/except instead

**Comment by CzendaZdenda** [comment]
You are right, CarlMears, I will fixed it as soo as possible.
